name: Update native version used

on:
  workflow_call:
    inputs:
      release_version:
        description: Define the specific release version?
        type: string
        required: true
      release_type:
        description: Specify the release type
        type: string
        required: true
      platform:
        description: Specify the platform to be updated
        type: string
        required: true

  workflow_dispatch:
    inputs:
      release_version:
        description: Define the specific release version?
        required: true
      release_type:
        description: Specify the release type
        required: true
        options:
          - minor
          - patch
      platform:
        type: choice
        description: Specify the platform to be updated
        required: true
        options:
          - android
          - ios
jobs:
  create_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pull-requests: write 
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: KaleyraVideo/VideoHybridNativeBridge
          path: videoHybridNativeBridge
          fetch-depth: 0
          fetch-tags: true
          ref: main
          token: ${{steps.generate_token.outputs.token}}
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
            GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
        with:
          branch: 'update_native'

  update_android_native_version:
    needs: create_branch
    if: ${{ github.event.inputs.platform == 'android' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./videoHybridNativeBridge
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: KaleyraVideo/VideoHybridNativeBridge
          path: videoHybridNativeBridge
          fetch-depth: 0
          fetch-tags: true
          ref: update_native
          token: ${{steps.generate_token.outputs.token}}
      - name: "Update the android version"
        run: sed -i 's/kaleyraVideoSdkVersion = "[0-9]*\.[0-9]*\.[0-9]*-*\w*"/kaleyraVideoSdkVersion = "'${{ github.event.inputs.release_version }}'"/g' ./android/bridge.gradle
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./videoHybridNativeBridge
          commit_message: "chore: Update android sdk version"
          tagging_message: android-v${{ github.event.inputs.release_version }}

  update_ios_native_version:
    needs: create_branch
    if: ${{ github.event.inputs.platform == 'ios' }}
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./videoHybridNativeBridge
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: KaleyraVideo/VideoHybridNativeBridge
          path: videoHybridNativeBridge
          fetch-depth: 0
          fetch-tags: true
          ref: update_native
          token: ${{steps.generate_token.outputs.token}}
      - name: "Update the ios version"
        run: |
            sed -i '' "s/pod 'KaleyraVideoSDK', '~> [0-9]*\.[0-9]*\.[0-9]*-*\w*'/ pod 'KaleyraVideoSDK', '~> "${{ github.event.inputs.release_version }}"'/g" ./iOS/Podfile
            cd iOS
            pod repo update
            pod cache clean --all
            pod deintegrate
            pod install --repo-update --clean-install
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./videoHybridNativeBridge
          commit_message: "chore: Update ios sdk version"
          tagging_message: ios-v${{ github.event.inputs.release_version }}
  
  create_pull_request:
    runs-on: ubuntu-latest
    needs: [update_android_native_version, update_ios_native_version]
    if: ${{ always() && !cancelled() && !contains(needs.*.result, 'failure') }}
    defaults:
      run:
        working-directory: ./videoHybridNativeBridge
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: KaleyraVideo/VideoHybridNativeBridge
          path: videoHybridNativeBridge
          fetch-depth: 0
          fetch-tags: true
          token: ${{steps.generate_token.outputs.token}}
      - name: Reset update_native branch
        run: |
          git fetch origin update_native:update_native
          git reset --hard update_native
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          path: videoHybridNativeBridge
          token: ${{steps.generate_token.outputs.token}}
          commit-message: 'chore: Update native version'
          branch: prepare_release_native
          title: 'Update native dependency'
          labels: |
              ${{ github.event.inputs.release_type }}
